FROM php:7.2-fpm-alpine3.8

# Install system packages & PHP extensions required for Yii 2.0 Framework
# virtual pkg names and ENV $PHPIZE_DEPS are definied in base image
# C* and LDFlAGS are also definied in base image, so we use these for our custom pecl builds
# we install (newer) imagick from edge repo due to SEGFAULT bugs
# hopefully this won't break other things...
RUN echo "Starting"
RUN echo "ipv6" >> /etc/modules
RUN apk add git
RUN apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS && \
    apk add --no-cache --virtual .imagemagick-edge \
            --repository http://dl-3.alpinelinux.org/alpine/v3.6/main/ \
            --allow-untrusted \
        imagemagick \
        imagemagick-dev && \
    apk add --update --virtual .pecl-build-deps \
        icu-dev \
        curl-dev \
        freetype-dev \
        pcre-dev \
        postgresql-dev \
        libtool \
#        libmcrypt-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        libxml2-dev && \
    apk add \
        git \
        curl \
        bash \
        bash-completion \
        icu \
        vim \
        pcre \
        sqlite \
        freetype \
 #       libmcrypt \
        libintl \
        libjpeg-turbo \
        imagemagick \
        libpng \
        libltdl \
        libxml2 \
        mysql-client \
        nodejs && \
    export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" && \
    pecl install \
        apcu \
 #       mcrypt \
        redis \
        imagick-3.4.3 && \
    docker-php-ext-enable imagick && \
    docker-php-ext-enable redis && \
#    docker-php-ext-enable mcrypt && \
    docker-php-ext-enable apcu && \
    docker-php-ext-configure gd \
        --with-gd \
        --with-freetype-dir=/usr/include/ \
        --with-png-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ && \
    docker-php-ext-configure bcmath && \
    docker-php-ext-install \
        soap \
        zip \
        curl \
        bcmath \
        exif \
        gd \
        iconv \
        intl \
        mbstring \
        pdo \
        pdo_mysql \
        opcache && \
    apk del \
        .pecl-build-deps .phpize-deps


# Install less-compiler
#RUN curl -sL https://deb.nodesource.com/setup_9.x | bash -
RUN apk add --update nodejs nodejs-npm

# Configure version constraints
ENV PHP_ENABLE_XDEBUG=1 \
    VERSION_COMPOSER_ASSET_PLUGIN=^1.4.2 \
    VERSION_PRESTISSIMO_PLUGIN=^0.3.7 \
    PATH=/app:/app/vendor/bin:/root/.composer/vendor/bin:$PATH \
    TERM=linux \
    COMPOSER_ALLOW_SUPERUSER=1


# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- \
        --filename=composer \
        --install-dir=/usr/local/bin && \
    composer global require --optimize-autoloader \
        "fxp/composer-asset-plugin:${VERSION_COMPOSER_ASSET_PLUGIN}" \
        "hirak/prestissimo:${VERSION_PRESTISSIMO_PLUGIN}" && \
    composer global dumpautoload --optimize && \
    composer clear-cache

WORKDIR /app/api
COPY ./api/composer.* /app/api/
RUN composer install --prefer-dist --optimize-autoloader && \
    composer clear-cache

# Application source-code
COPY ./ /app


WORKDIR /app
# Permissions; run yii commands as webserver user
#ENV PHP_USER_ID=82
RUN mkdir -p runtime web/assets web/bundles /mnt/storage && \
    chmod -R 775 runtime web/assets web/bundles /mnt/storage && \
    chmod -R ugo+r /root/.composer/vendor && \
    chown -R www-data:www-data runtime web/assets web/bundles /root/.composer/vendor /mnt/storage #&& \
    #APP_NO_CACHE=1 APP_LANGUAGES=en yii asset/compress src/config/assets.php web/bundles/config.php